# Azure-DEV docker
FROM node:12.2.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ENV REACT_APP_API_HOST https://haveblue-django.azurewebsites.net/api/1.0
ENV REACT_APP_API_MOCK false
ENV REACT_APP_API_MOCK_HOST /api/1.0

ENV REACT_APP_LSDB_BUILD DEVELOPMENT

COPY webclient/package.json /app/package.json
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent
COPY webclient/ /app
COPY asimov/azdev/node.env /app/.env

RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY asimov/azdev/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
