# DEV-Local docker
FROM node:12.2.0-alpine
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ENV REACT_APP_API_HOST http://localhost:8000/api/1.0
ENV REACT_APP_API_MOCK false
#ENV REACT_APP_API_MOCK_HOST /api/1.0
ENV REACT_APP_LSDB_BUILD DEVELOPMENT
COPY webclient/package.json /app/package.json
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent

# When we have a test deployment, we'll need this:
#COPY ./local_dev.env ./.env
# start app
CMD ["npm", "start"]
