# Generated by Django 3.1.2 on 2020-11-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_facet_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgfile',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
