# Generated by Django 3.1.2 on 2020-11-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201031_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgfile',
            name='name',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
