# Generated by Django 3.1.2 on 2020-11-01 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20201031_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgfile',
            name='name',
        ),
    ]
