# Generated by Django 3.1.2 on 2020-12-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_imgfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgfile',
            name='linkedImages',
            field=models.ManyToManyField(blank=True, to='post.ImgFile'),
        ),
        migrations.AlterField(
            model_name='region',
            name='height',
            field=models.TextField(max_length=4),
        ),
        migrations.AlterField(
            model_name='region',
            name='width',
            field=models.TextField(max_length=4),
        ),
        migrations.AlterField(
            model_name='region',
            name='x',
            field=models.TextField(max_length=4),
        ),
        migrations.AlterField(
            model_name='region',
            name='y',
            field=models.TextField(max_length=4),
        ),
    ]
