# Generated by Django 3.1.2 on 2020-12-08 22:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_link_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=None),
            preserve_default=False,
        ),
    ]
