# Generated by Django 3.1.2 on 2020-12-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_node_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='destination',
            new_name='target',
        ),
    ]
